/* eslint-disable import/no-anonymous-default-export */
export default {
  name: "genre",
  title: "Genre",
  type: "string",
  options: {
    list: [
      { title: "Sci-Fi", value: "Sci-Fi" },
      { title: "Historical", value: "Historical" },
      { title: "Classic", value: "Classic" },
      { title: "Mystery", value: "Mystery" },
      { title: "Horror", value: "Horror" },
      { title: "Fantasy", value: "Fantasy" },
      { title: "Literary", value: "Literary" },
      { title: "Philosophical", value: "Philosophical" },
      { title: "Science", value: "Science" },
      { title: "Short Stories", value: "Short stories" },
      { title: "Poetry", value: "Poetry" },
      { title: "Biography", value: "Biography" },
      { title: "Sports", value: "Sports" },
      { title: "Business", value: "Business" },
      { title: "Architecture", value: "Architecture" },
      { title: "Self Help", value: "Self help" },
      { title: "Philosophical", value: "Philosophical" },
      { title: "Fantasy", value: "Fantasy" },
      { title: "Literary", value: "Literary" },
      { title: "Memoir", value: "Memoir" },
      { title: "Health", value: "Health" },
      { title: "Technology", value: "Technology" },
    ],
  },
}
